language: php
php:
    - 7.0

script: phpunit

before_script: 
    - composer self-update 
    - composer install --prefer-dist
    - composer autoloaddump -o

branches:
  only:
    - master
